###
# Avoid syncing from prometheus/prometheus: no_prometheus_repo_sync
###
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    directories:
      - /.github/workflows
      - /build
      - /examples
      - /publish_main
      - /publish_release
    schedule:
      interval: "monthly"
    groups:
      promci:
        patterns:
          - "prometheus/promci*"
      codeql:
        patterns:
          - "github/codeql-action*"
    # Exclude configs synced from upstream prometheus/prometheus.
    exclude-paths:
      - .github/workflows/approve-workflows.yml
      - .github/workflows/container_description.yml
      - .github/workflows/golangci-lint.yml
      - .github/workflows/govulncheck.yml
      - .github/workflows/scorecards.yml
      - .github/workflows/stale.yml
