version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: actions/restore_artifacts
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: actions/save_artifacts
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: actions/setup_environment
    schedule:
      interval: "weekly"
