version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /.github/workflows
      - /build
      - /publish_main
      - /publish_release
    schedule:
      interval: "weekly"
