name: PromCI
description: An action used by the Prometheus project to share github actions.
runs:
  using: composite
  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: 'prometheus/promci'
        path: '.github/promci'
        ref: v0.0.2
