name: PromCI
description: An action used by the Prometheus project to share github actions.
runs:
  using: composite
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        repository: 'prometheus/promci'
        path: '.github/promci'
        ref: v0.5.3
