name: PromCI
description: An action used by the Prometheus project to share github actions.
runs:
  using: composite
  steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        repository: 'prometheus/promci'
        path: '.github/promci'
        ref: v0.4.4
