name: Setup environment
inputs:
  enable_go:
    type: boolean
    description: Whether to enable go specific features, such as caching.
    default: true
  enable_npm:
    type: boolean
    description: Whether to enable npm specific features, such as caching.
    default: false
  enable_docker_multibuild:
    type: boolean
    description: Whether to enable multibuild docker
    default: false
  memlimit_ratio:
    type: string
    description: The ratio of memory reserved for Go
    default: "0.8"
  clean-runner-disk:
    type: boolean
    description: Whether to enable try to free up disk space on the runner.
    default: false
runs:
  using: composite
  steps:
    - name: Aggressive cleanup
      shell: bash
      if: inputs.clean-runner-disk== 'true'
      run: |
        df -h
        # Remove Java (JDKs)
        sudo rm -rf /usr/lib/jvm

        # Remove .NET SDKs
        sudo rm -rf /usr/share/dotnet

        # Remove Swift toolchain
        sudo rm -rf /usr/share/swift

        # Remove Haskell (GHC)
        sudo rm -rf /usr/local/.ghcup

        # Remove Julia
        sudo rm -rf /usr/local/julia*

        # Remove Android SDKs
        sudo rm -rf /usr/local/lib/android

        # Remove Chromium (optional if not using for browser tests)
        sudo rm -rf /usr/local/share/chromium

        # Remove Microsoft/Edge and Google Chrome builds
        sudo rm -rf /opt/microsoft /opt/google

        # Remove Azure CLI
        sudo rm -rf /opt/az

        # Remove PowerShell
        sudo rm -rf /usr/local/share/powershell

        df -h
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: inputs.enable_go == 'true'
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: inputs.enable_npm == 'true'
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('web/ui/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Set GOMEMLIMIT
      shell: bash
      run: |
        ratio=${{ inputs.memlimit_ratio }}
        cgroup=$(awk -F':' '{print $3}' /proc/self/cgroup)
        cgroup_mem_limit=$(< "/sys/fs/cgroup/${cgroup}/memory.max")
        if [[ "${cgroup_mem_limit}" != "max" ]] ; then
          echo "${cgroup_mem_limit}" | awk -v "ratio=${ratio}" '{printf "GOMEMLIMIT=%.0fKiB\n", $1 / 1024 * ratio}' >> "$GITHUB_ENV"
          exit 0
        fi
        awk -v "ratio=${ratio}" '$1 == "MemTotal:" {printf "GOMEMLIMIT=%.0fKiB\n", $2 * ratio}' /proc/meminfo >> "$GITHUB_ENV"
      if: inputs.enable_go == 'true'
    - run: echo "GOMEMLIMIT=${GOMEMLIMIT}"
      shell: bash
      if: inputs.enable_go == 'true'
    - run: make promu
      shell: bash
      if: inputs.enable_go == 'true'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      if: inputs.enable_docker_multibuild == 'true'
    - name: Set up buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      if: inputs.enable_docker_multibuild == 'true'
