name: Setup environment
inputs:
  enable_go:
    type: boolean
    description: Whether to enable go specific features, such as caching.
    default: true
  enable_npm:
    type: boolean
    description: Whether to enable npm specific features, such as caching.
    default: false
  enable_docker_multibuild:
    type: boolean
    description: Whether to enable multibuild docker
    default: false
  memlimit_ratio:
    type: string
    description: The ratio of memory reserved for Go
    default: "0.8"
runs:
  using: composite
  steps:
    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      if: inputs.enable_go == 'true'
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      if: inputs.enable_npm == 'true'
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('web/ui/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Set GOMEMLIMIT
      shell: bash
      run: |
        ratio=${{ inputs.memlimit_ratio }}
        cgroup=$(awk -F':' '{print $3}' /proc/self/cgroup)
        cgroup_mem_limit=$(< "/sys/fs/cgroup/${cgroup}/memory.max")
        if [[ "${cgroup_mem_limit}" != "max" ]] ; then
          echo "${cgroup_mem_limit}" | awk -v "ratio=${ratio}" '{printf "GOMEMLIMIT=%.0fKiB\n", $1 / 1024 * ratio}' >> "$GITHUB_ENV"
          exit 0
        fi
        awk -v "ratio=${ratio}" '$1 == "MemTotal:" {printf "GOMEMLIMIT=%.0fKiB\n", $2 * ratio}' /proc/meminfo >> "$GITHUB_ENV"
      if: inputs.enable_go == 'true'
    - run: echo "GOMEMLIMIT=${GOMEMLIMIT}"
      shell: bash
      if: inputs.enable_go == 'true'
    - run: make promu
      shell: bash
      if: inputs.enable_go == 'true'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      if: inputs.enable_docker_multibuild == 'true'
    - name: Set up buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      if: inputs.enable_docker_multibuild == 'true'
