name: Setup environment
inputs:
  enable_go:
    type: boolean
    description: Whether to enable go specific features, such as caching.
    default: true
  enable_npm:
    type: boolean
    description: Whether to enable npm specific features, such as caching.
    default: false
  enable_docker_multibuild:
    type: boolean
    description: Whether to enable multibuild docker
    default: false
  memlimit_ratio:
    type: string
    description: The ratio of memory reserved for Go
    default: "0.8"
runs:
  using: composite
  steps:
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      if: inputs.enable_go == 'true'
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      if: inputs.enable_npm == 'true'
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('web/ui/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Set GOMEMLIMIT
      shell: bash
      run: |
        ratio=${{ inputs.memlimit_ratio }}
        cgroup=$(awk -F':' '{print $3}' /proc/self/cgroup)
        cgroup_mem_limit=$(< "/sys/fs/cgroup/${cgroup}/memory.max")
        if [[ "${cgroup_mem_limit}" != "max" ]] ; then
          echo "${cgroup_mem_limit}" | awk -v "ratio=${ratio}" '{printf "GOMEMLIMIT=%.0fKiB\n", $1 / 1024 * ratio}' >> "$GITHUB_ENV"
          exit 0
        fi
        awk -v "ratio=${ratio}" '$1 == "MemTotal:" {printf "GOMEMLIMIT=%.0fKiB\n", $2 * ratio}' /proc/meminfo >> "$GITHUB_ENV"
      if: inputs.enable_go == 'true'
    - run: echo "GOMEMLIMIT=${GOMEMLIMIT}"
      shell: bash
      if: inputs.enable_go == 'true'
    - run: make promu
      shell: bash
      if: inputs.enable_go == 'true'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
      if: inputs.enable_docker_multibuild == 'true'
    - name: Set up buildx
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      if: inputs.enable_docker_multibuild == 'true'
