name: Publish release image
inputs:
  registry:
    type: string
    description: Docker registry
  organization:
    type: string
    description: Organization
  login:
    type: string
    description: Username
  password:
    type: string
    description: Password
  dockerfile_path:
    description: Path to Dockerfile
    type: string
    default: ""
  dockerbuild_context:
    description: Path to Dockerbuild context
    type: string
    default: ""
  container_image_name:
    description: Name of the container image
    type: string
    default: ""
runs:
  using: composite
  steps:
    - if: inputs.dockerfile_path != ''
      run: echo "export DOCKERFILE_PATH=${{ inputs.dockerfile_path }}" >> /tmp/tmp-profile
      shell: bash
    - if: inputs.container_image_name != ''
      run: echo "export DOCKER_IMAGE_NAME=${{ inputs.container_image_name }}" >> /tmp/tmp-profile
      shell: bash
    - if: inputs.dockerbuild_context != ''
      run: echo "export DOCKERBUILD_CONTEXT=${{ inputs.dockerbuild_context }}" >> /tmp/tmp-profile
      shell: bash
    - run: |
        current_tag=${GITHUB_REF#refs/*/}
        touch /tmp/tmp-profile
        . /tmp/tmp-profile
        make docker DOCKER_IMAGE_TAG="$current_tag" DOCKER_REPO=${{ inputs.registry }}/${{ inputs.organization }}
        docker images
        echo ${{ inputs.password }} | docker login -u ${{ inputs.login }} --password-stdin ${{ inputs.registry }}
        make docker-publish DOCKER_IMAGE_TAG="$current_tag" DOCKER_REPO=${{ inputs.registry }}/${{ inputs.organization }}
        make docker-manifest DOCKER_IMAGE_TAG="$current_tag" DOCKER_REPO=${{ inputs.registry }}/${{ inputs.organization }}
        if [[ "$current_tag" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
          # Get the latest stable release tag (excluding pre-releases)
          latest_tag=$(git tag -l 'v*' | grep -P '^v\d+\.\d+\.\d+$' | sort -V -r | head -n1)
          echo "Current tag: $current_tag"
          echo "Latest stable tag: $latest_tag"

          # Only push "latest" tags if this is the latest stable release
          if [[ "${current_tag}" == "${latest_tag}" ]]; then
            echo "This is the latest stable release, pushing 'latest' tags"
            make docker-tag-latest DOCKER_IMAGE_TAG="$current_tag" DOCKER_REPO=${{ inputs.registry }}/${{ inputs.organization }}
            make docker-publish DOCKER_IMAGE_TAG="latest" DOCKER_REPO=${{ inputs.registry }}/${{ inputs.organization }}
            make docker-manifest DOCKER_IMAGE_TAG="latest" DOCKER_REPO=${{ inputs.registry }}/${{ inputs.organization }}
          else
            echo "Skipping 'latest' tags - $current_tag is not the latest stable release"
          fi
        fi
      shell: bash
