# Tar is used because the default actions do not preserve directory structure
# and file mode.
name: Save artifacts
inputs:
  directory:
    type: string
    description: Path of the directory to save
runs:
  using: composite
  steps:
    - run: |
        tar cvf artifact.tar ${{ inputs.directory }}
        mv artifact.tar artifact-$(sha1sum artifact.tar|awk '{ print $1 }').tar
      shell: bash
    - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        path: artifact-*.tar
