# Tar is used because the default actions do not preserve directory structure
# and file mode.
name: Save artifacts
inputs:
  directory:
    type: string
    description: Path of the directory to save
runs:
  using: composite
  steps:
    - run: |
        tar cvf artifact.tar ${{ inputs.directory }}
        mv artifact.tar artifact-$(sha1sum artifact.tar|awk '{ print $1 }').tar
      shell: bash
    - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        path: artifact-*.tar
