---
name: CI
on:
  pull_request:
  push:
    branches: [main, 'release-*']
    tags: ['v*']

permissions:
  contents: read

jobs:
  test:
    name: Test actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate Workflows and Custom Actions
        uses: mpalmer/action-validator@c994f427b7c42cd5ecb1bc9315cb91c3d7d72e3d # v0.9.0
        with:
          patterns: |-
            .github/workflows/*.yml
            approve_workflows/action.yml
            build/action.yml
            publish_main/action.yml
            publish_release/action.yml
