# Restore artifacts created by save_artifacts.
# Tar is used because the default actions do not preserve directory structure
# and file mode.
name: Restore artifacts
runs:
  using: composite
  steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        pattern: artifact-*
        merge-multiple: true
        path: .artifacts
    - run: |
        for tar in .artifacts/*.tar
        do
          tar xvf $tar
          rm $tar
        done
      shell: bash
