# Restore artifacts created by save_artifacts.
# Tar is used because the default actions do not preserve directory structure
# and file mode.
name: Restore artifacts
runs:
  using: composite
  steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: tarballs
        path: .artifacts
    - run: |
        for tar in .artifacts/*.tar
        do
          tar xvf $tar
        done
        rm -v .artifacts/*.tar
      shell: bash
